version: '2'

services:
  vault:
    container_name: vault-eth-test
    image: vault-test:1.0
    ports:
      - 8200:8200
      - 8201:8201
    environment:
      - VAULT_ADDR=https://0.0.0.0:8200
      - VAULT_CACERT=/etc/vault.d/root.crt
    cap_add:
      - IPC_LOCK
    command: nohup /usr/local/bin/vault server -config /etc/vault.d/vault.hcl &> /dev/null &
