version: '2'

services:
  web:
    container_name: vault-eth-test
    image: vault-test:2.0
    ports:
      - 8200:8200
      - 8201:8201
    environment:
      - VAULT_ADDR=https://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: vault server -config /etc/vault.d/vault.hcl